### ISSUE TITLE
MicroHack/03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/Challenge 2

### ISSUE THREAD

**Issue by TheFitzZZ** [microsoft/MicroHack#18]
Walkthrough references now outdated legacy method, should be moved to Data Collection Rules.

To mitigate, update screenshots to reflect portal changes:

Portal:
![image](https://user-images.githubusercontent.com/13013440/210533653-9832689a-d623-497e-8a0c-6ed35f2db9ef.png)

Currently in docs:
![image](https://user-images.githubusercontent.com/13013440/210533725-04f0aee3-3944-4ee8-9548-78c69a736223.png)

**Comment by cthoenes** [comment]
@adriandiver is it possible to update the screenshot to reflect the new portal experience?
