### ISSUE TITLE
02_Hybrid_Azure_Arc_Servers - Challenge 5 - Streamline AZ and PoSh usage to use either the one or the other

### ISSUE THREAD

**Issue by ASchwarz1984** [microsoft/MicroHack#21]
https://github.com/microsoft/MicroHack/blob/8e03ad7756ad565af2d4963d94fd7e0e5ca19013/03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/walkthrough/challenge-5/solution.md?plain=1#L90

**Comment by cthoenes** [comment]
@ASchwarz1984 done PR #25 thanks for you feedback.
