### ISSUE TITLE
01-03-Infrastructure 02_Hybrid_Azure_Arc_Servers - Challenge 2 - Azure Policy deployment of Linux agents will fail if Ubuntu 22.04.1 is used.

### ISSUE THREAD

**Issue by ASchwarz1984** [microsoft/MicroHack#24]
If Ubuntu 22.04.1 is used the deployment of Log Analytics and Dependency Agent for Linux will fail.

**Comment by cthoenes** [comment]
Prerequisites should include a Hint for this.

**Comment by chrochma** [comment]
@cthoenes, resolved as we removed the Log Analytics Agent. Azure Monitoring Agent is the replacement. MicroHack was updated with the replacement.
