### ISSUE TITLE
bicep link in pre-req points to forked repo

### ISSUE THREAD

**Issue by sforstre** [microsoft/MicroHack#56]
"this Bicep script" points to angerl repo instead microsoft/MicroHack

https://github.com/microsoft/MicroHack/blob/main/03-Azure/01-03-Infrastructure/01_Azure_Virtual_Desktop/Challenges/00-Pre-Reqs.md#setup-your-networking-and-resource-groups-structure

**Comment by anggerl** [comment]
fixed
