### ISSUE TITLE
MicroHack/03-Azure/01-03-Infrastructure /06_Migration_Datacentre_Modernization Parameterize Location of Bicep Deployments

### ISSUE THREAD

**Issue by cthoenes** [microsoft/MicroHack#57]
We need to allow an deployment parameter for the location of the deployments to accomodate for potential restrictions in the respective subscription

**Comment by L480** [comment]
https://github.com/microsoft/MicroHack/commit/a6904e4323a13c25830b837ba417f6e964f47598
