### ISSUE TITLE
[Feature] Add ability to create multiple instances of the deployment

### ISSUE THREAD

**Issue by jonas-wanninger** [microsoft/MicroHack#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Microhack

03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization

### Feature Description

During the Microhack workshop, it can be quite time-consuming to deploy the initial required infrastructure. It would be nice to be able to make multiple deployments, so the environment can be prepared quickly before the event. 

Proposed Features:
- Specify number of participants and deploy x instances of the Microhack infra
- Automatically provision throw-away user accounts and apply the appropriate RBAC permissions
  - Users should only see their own infrastructure and not from other Microhack participants

**Comment by cthoenes** [comment]
Deployment of Multiple instances in one Subscription successfully tested.
User assignment would need special solution will be evaluated.
